In [1]:
import pandas as pd

In [10]:
data = pd.read_csv('C:\\Users\\Liman\Downloads\\Partially Cleaned Salary Dataset.csv')
data

,Unnamed: 0,Company Name,Job Title,Salaries Reported,Location,Salary
0,0,Mu Sigma,Data Scientist,105,Bangalore,648573.0
1,1,IBM,Data Scientist,95,Bangalore,1191950.0
2,2,Tata Consultancy Services,Data Scientist,66,Bangalore,836874.0
3,3,Impact Analytics,Data Scientist,40,Bangalore,669578.0
4,4,Accenture,Data Scientist,32,Bangalore,944110.0
...,...,...,...,...,...,...
4334,4339,TaiyōAI,Machine Learning Scientist,1,Mumbai,62160.0
4335,4340,Decimal Point Analytics,Machine Learning Developer,1,Mumbai,751286.0
4336,4341,MyWays,Machine Learning Developer,1,Mumbai,410952.0
4337,4342,Market Pulse Technologies,Software Engineer - Machine Learning,1,Mumbai,1612324.0
4338,4343,vPhrase,Machine Learning Engineer,1,Mumbai,939843.0

In [12]:
data.drop(columns=['Unnamed: 0'],inplace=True)
data

,Company Name,Job Title,Salaries Reported,Location,Salary
0,Mu Sigma,Data Scientist,105,Bangalore,648573.0
1,IBM,Data Scientist,95,Bangalore,1191950.0
2,Tata Consultancy Services,Data Scientist,66,Bangalore,836874.0
3,Impact Analytics,Data Scientist,40,Bangalore,669578.0
4,Accenture,Data Scientist,32,Bangalore,944110.0
...,...,...,...,...,...
4334,TaiyōAI,Machine Learning Scientist,1,Mumbai,62160.0
4335,Decimal Point Analytics,Machine Learning Developer,1,Mumbai,751286.0
4336,MyWays,Machine Learning Developer,1,Mumbai,410952.0
4337,Market Pulse Technologies,Software Engineer - Machine Learning,1,Mumbai,1612324.0
4338,vPhrase,Machine Learning Engineer,1,Mumbai,939843.0

In [14]:
data.to_csv('cleaned_salary_dataset.csv', index= False)

In [15]:
data.to_excel('cleaned_salary_dataset.xlsx', index = False)