## 🛒 Apriori Situation: Market Basket Analysis

Imagine you're a **Machine Learning Engineer** working for a supermarket. Your goal? 🧠 Discover valuable patterns in customer purchases to help improve business decisions.

Your employer hands you a dataset containing customer transactions that looks like this:

In [1]:
dataset = [ ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Milk', 'Apple', 'Kidney Beans', 'Eggs'], ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'], ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs'] ]

🧾 Transaction Format: Each inner list in our dataset represents a **transaction** — a purchase made by a customer

## 🛠️ Apriori Preparation

Before applying the **Apriori algorithm**, we need to **preprocess our dataset** properly.

### 🔄 One-Hot Encoding

The Apriori function requires a dataset where:
- Each **row** represents a transaction
- Each **column** represents a unique item
- Each **cell** contains either **True** or **False** indicating the presence or absence of that item in the transaction

This transformation is known as **one-hot encoding**.

### 🧰 Using `TransactionEncoder`

To achieve this, we use the `TransactionEncoder` class from the **`mlxtend`** library. It:
- Takes a list of transactions as input
- Returns a NumPy array with boolean values (True/False)
- Not 0/1 — but functionally the same idea

In [2]:
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

## 📊 Support Code – Filtering Itemsets by Support

Now that the dataset has been transformed using one-hot encoding, we can move on to **extracting frequent itemsets** using the **Apriori algorithm**.

🎯 Goal: We want to find itemsets that appear in **at least 60%** of all transactions — this is called setting the **minimum support threshold**.

In [3]:
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.6)

    support   itemsets
0       0.8        (3)
1       1.0        (5)
2       0.6        (6)
3       0.6        (8)
4       0.6       (10)
5       0.8     (3, 5)
6       0.6     (8, 3)
7       0.6     (5, 6)
8       0.6     (8, 5)
9       0.6    (10, 5)
10      0.6  (8, 3, 5)

### Support with column names

In [ ]:
frequent_itemsets=apriori(df, min_support=0.6, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Eggs, Kidney Beans)
6       0.6                (Eggs, Onion)
7       0.6         (Milk, Kidney Beans)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Yogurt, Kidney Beans)
10      0.6  (Eggs, Onion, Kidney Beans)

## ✅ Confidence-Based Rule Extraction

Once we have our frequent itemsets, we can extract **association rules** using other interesting metrics like **confidence** and **lift**.

In [ ]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7) # associate items

c:\Users\saids\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,1.0,0.00,inf,0.0,0.80,0.000,0.900
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,1.0,0.00,1.0,0.0,0.80,0.000,0.900
2,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
3,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
7,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
8,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
9,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
10,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
11,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875

## 🚀 Lift-Based Rule Extraction

In addition to **confidence**, we can also use **lift** as a metric to extract more meaningful association rules.

In [ ]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets,metric="lift",min_threshold=1.25)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
1,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
2,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875

# Association Rule Mining Metrics

## 📌 Basic Components
- **Antecedents**: Items on the **left side** of the rule (e.g., `{Milk} → {Bread}`, where "Milk" is the antecedent).
- **Consequents**: Items on the **right side** of the rule (e.g., "Bread" in the above example).

## 📊 Key Metrics

| **Metric**            | **Definition** | **Formula / Explanation** |
|----------------------|--------------|---------------------------|
| **Antecedent Support** | Probability of antecedent occurring | `Support(A) = Transactions(A) / Total Transactions` |
| **Consequent Support** | Probability of consequent occurring | `Support(B) = Transactions(B) / Total Transactions` |
| **Support**          | How often both antecedent & consequent appear together | `Support(A → B) = Transactions(A, B) / Total Transactions` |
| **Confidence**       | Likelihood of B appearing given that A appears | `Confidence(A → B) = Support(A, B) / Support(A)` |
| **Lift**            | Strength of association compared to random occurrence | `Lift(A → B) = Confidence(A → B) / Support(B)` |
| **Representativity** | Indicates how well a rule represents the dataset | Measures how frequent a rule appears |
| **Leverage**        | Difference between actual & expected support if A and B were independent | `Leverage(A → B) = Support(A, B) - (Support(A) * Support(B))` |
| **Conviction**      | Measures dependency between antecedent & consequent | `Conviction(A → B) = (1 - Support(B)) / (1 - Confidence(A → B))` |
| **Zhang's Metric**  | Balances impact of both antecedent and consequent | Measures how interesting the rule is |
| **Jaccard**         | Similarity between itemsets | `Jaccard(A, B) = Support(A, B) / (Support(A) + Support(B) - Support(A, B))` |
| **Certainty**       | Reliability of rule based on confidence and dataset | Helps gauge strength of rule |
| **Kulczynski**      | Balances confidence in **both directions** | `Kulczynski(A → B) = (Confidence(A → B) + Confidence(B → A)) / 2` |

## 🎯 Summary
Association rule mining helps uncover hidden patterns in datasets by evaluating relationships between items using **support, confidence, lift**, and other statistical metrics.