In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('C:\\Users\\Liman\\Downloads\\amazon_sales_dataset.csv')
df.head(3)

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [22]:
df['order_date'] = pd.to_datetime(df['order_date'])

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['day'] = df['order_date'].dt.day

In [23]:
df = df.drop('order_date', axis= 1)

In [24]:
df.head(1)

,order_id,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,year,month,day
0,1,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,2022,4,13

In [25]:
df['payment_method'].unique()

array(['UPI', 'Credit Card', 'Wallet', 'Cash on Delivery', 'Debit Card'],
      dtype=object)

In [26]:
df['customer_region'].unique()

array(['North America', 'Asia', 'Europe', 'Middle East'], dtype=object)

In [27]:
df['product_category'].unique()

array(['Books', 'Fashion', 'Sports', 'Beauty', 'Electronics',
       'Home & Kitchen'], dtype=object)

In [28]:
df = pd.get_dummies(df , columns=['product_category','payment_method','customer_region'])

In [29]:
df.head(2)

,order_id,product_id,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue,year,...,product_category_Sports,payment_method_Cash on Delivery,payment_method_Credit Card,payment_method_Debit Card,payment_method_UPI,payment_method_Wallet,customer_region_Asia,customer_region_Europe,customer_region_Middle East,customer_region_North America
0,1,2637,128.75,10,4,3.5,443,115.88,463.52,2022,...,False,False,False,False,True,False,False,False,False,True
1,2,2300,302.60,20,5,3.7,475,242.08,1210.40,2023,...,False,False,True,False,False,False,True,False,False,False

In [32]:
df = df.drop('order_id',axis=1)

In [33]:
df = df.drop('product_id', axis=1)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            50000 non-null  float64
 1   discount_percent                 50000 non-null  int64
 2   quantity_sold                    50000 non-null  int64
 3   rating                           50000 non-null  float64
 4   review_count                     50000 non-null  int64
 5   discounted_price                 50000 non-null  float64
 6   total_revenue                    50000 non-null  float64
 7   year                             50000 non-null  int32
 8   month                            50000 non-null  int32
 9   day                              50000 non-null  int32
 10  product_category_Beauty          50000 non-null  bool
 11  product_category_Books           50000 non-null  bool
 12  product_category_Electronics     50000 non-null  bool
 13  product_category_Fashion         50000 non-null  bool
 14  product_category_Home & Kitchen  50000 non-null  bool
 15  product_category_Sports          50000 non-null  bool
 16  payment_method_Cash on Delivery  50000 non-null  bool
 17  payment_method_Credit Card       50000 non-null  bool
 18  payment_method_Debit Card        50000 non-null  bool
 19  payment_method_UPI               50000 non-null  bool
 20  payment_method_Wallet            50000 non-null  bool
 21  customer_region_Asia             50000 non-null  bool
 22  customer_region_Europe           50000 non-null  bool
 23  customer_region_Middle East      50000 non-null  bool
 24  customer_region_North America    50000 non-null  bool
dtypes: bool(15), float64(4), int32(3), int64(3)
memory usage: 4.0 MB

In [53]:
df.isnull().sum()

price                              0
discount_percent                   0
quantity_sold                      0
rating                             0
review_count                       0
discounted_price                   0
total_revenue                      0
year                               0
month                              0
day                                0
product_category_Beauty            0
product_category_Books             0
product_category_Electronics       0
product_category_Fashion           0
product_category_Home & Kitchen    0
product_category_Sports            0
payment_method_Cash on Delivery    0
payment_method_Credit Card         0
payment_method_Debit Card          0
payment_method_UPI                 0
payment_method_Wallet              0
customer_region_Asia               0
customer_region_Europe             0
customer_region_Middle East        0
customer_region_North America      0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.describe()

,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue,year,month,day
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.0000,50000.000000
mean,252.507260,13.340700,2.999400,2.996316,249.329280,218.886566,657.331475,2022.501480,6.5044,15.790820
std,143.025544,9.850694,1.415401,1.154295,144.251981,127.317681,526.223968,0.500003,3.4360,8.799767
min,5.010000,0.000000,1.000000,1.000000,0.000000,3.530000,3.840000,2022.000000,1.0000,1.000000
25%,127.840000,5.000000,2.000000,2.000000,125.000000,109.680000,240.320000,2022.000000,4.0000,8.000000
50%,252.970000,10.000000,3.000000,3.000000,250.000000,215.805000,505.410000,2023.000000,7.0000,16.000000
75%,376.335000,20.000000,4.000000,4.000000,374.000000,322.702500,968.970000,2023.000000,9.0000,23.000000
max,499.990000,30.000000,5.000000,5.000000,499.000000,499.910000,2499.550000,2023.000000,12.0000,31.000000

In [47]:
df.head(1)

,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue,year,month,day,...,product_category_Sports,payment_method_Cash on Delivery,payment_method_Credit Card,payment_method_Debit Card,payment_method_UPI,payment_method_Wallet,customer_region_Asia,customer_region_Europe,customer_region_Middle East,customer_region_North America
0,128.75,10,4,3.5,443,115.88,463.52,2022,4,13,...,False,False,False,False,True,False,False,False,False,True

In [48]:
columns = ['price','total_revenue', 'discounted_price' ,'review_count' ,'discount_percent']

for col in columns :
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    IQR = q3 - q1

    lower = q1 - 1.5 * IQR 
    upper = q3 + 1.5 * IQR 

    outliers = df[(df[col]<lower) | (df[col] > upper)]
    print(col ,':', len(outliers))

price : 0
total_revenue : 752
discounted_price : 0
review_count : 0
discount_percent : 0

In [40]:
X = df.drop('total_revenue', axis=1)
y = df['total_revenue']

In [41]:
from sklearn.model_selection import train_test_split

X_train , y_train , X_test ,y_test = train_test_split (X ,y ,test_size=0.3,random_state=42)

In [43]:
X = df.drop('total_revenue', axis=1)
y = df['total_revenue']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

from xgboost import XGBRegressor

model = XGBRegressor()
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [49]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score , root_mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test , y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 2.2532377269045516
MSE: 9.80241536124132
RMSE: 3.1308809241555835
R2 Score: 0.9999639040805731

In [52]:
import joblib

joblib.dump(model, "xgb_model.pkl")

['xgb_model.pkl']